pipeline {
    agent any

    environment {
        IMAGE_NAME = "rahuljangra/ci-cd-app"
    }

    stages {

        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/RahulJangra79/cicd-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('app') {
                    bat '''
                    docker rmi -f %IMAGE_NAME% || echo image not found
                    docker build -t %IMAGE_NAME% .
                    '''                
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    bat 'docker login -u %USER% -p %PASS%'
                }
                bat 'docker push %IMAGE_NAME%'
            }
        }

        stage('Deploy to EC2') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'ec2-key', keyFileVariable: 'KEY')]) {
                    bat """
                    icacls %KEY% /inheritance:r
                    icacls %KEY% /grant:r "Users":R

                    ssh -o StrictHostKeyChecking=no -i %KEY% ubuntu@43.204.235.175 ^
                    "docker pull rahuljangra/ci-cd-app && ^
                    docker rm -f app || true && ^
                    docker run -d -p 3000:3000 --name app rahuljangra/ci-cd-app"
                    """
                }
            }
        }
    }
}
